### ISSUE TITLE
Docs on http://docs.honeybeeit.apiary.io incomplete

### ISSUE THREAD

**Issue by jumper85** [honeybee-it/api-docs#1]
Hi,

I think about subscribing to the VIP API access to get schedules, but the documentation mentioned in the title is not working correctly. Only the first call of every group is described completely.

The documentation here in the wiki doesn't seem to be complete either.

Can you check that please?

Thanks

**Comment by jnylen** [comment]
Hi @jumper85,

The docs on http://docs.honeybeeit.apiary.io/ is now fixed.
