### ISSUE TITLE
API issue with german channel Vox

### ISSUE THREAD

**Issue by jumper85** [honeybee-it/api-docs#2]
Hi,

I don't know if this is the right place for this but I didn't find anything else to report this issue. BTW: Is the Google+ Group still maintained? I tried to get access, but nothing happens.

The issue: I used the xmltv.se files before switching to the honeybee API and vox.de/hd.vox.de worked without any problems.

The API won't give me any program data. I get the batches but if I try to access the program for a specific batch, it only returns an empty array.

Can you check that please? And can you tell me where to report such things in the future?

Thanks in advance.

**Comment by jnylen** [comment]
Hi @jumper85 

It is, can you tell me the name you have on G+ and i'll accept it. There is non VIP Plus users applying so I haven't accepted those. It will be moved to a forums later on.

Thanks for reporting that issue, i'll investigate why it doesn't have data.

**Comment by jumper85** [comment]
Hi,

thanks for the quick response, I applied with LakeCycle but I don't know if thats the name it is shown to you.

So if I'm in the group and have some trouble, just post it to this group?

**Comment by jnylen** [comment]
I'm running all of the batches again as it just seems they just haven't been run for some reason (not sure why).
I'll check back a bit later tonight or tomorrow.

Accepted you to the G+ group. You can either post it in there or email me if you want to keep it secret.

**Comment by jnylen** [comment]
By the way, there is always http://status.jnylen.nu/ that checks all part of my servers and sites.

**Comment by jnylen** [comment]
Should be fixed now.
